[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[BASE]
source = "container"
container = "library/python"
include_regex = "\\d+\\.\\d+\\.?\\d?-alpine\\d\\.\\d+"

[TORNADO]
source = "pypi"
pypi = "tornado"

[PYCURL]
source = "pypi"
pypi = "pycurl"

[NVCHECKER]
source = "pypi"
pypi = "nvchecker"

[PACKAGING]
source = "pypi"
pypi = "packaging"

[PYALPM]
source = "gitlab"
gitlab = "archlinux/pyalpm"
host = "gitlab.archlinux.org"
use_max_tag = "true"

[AWESOMEVERSION]
source = "pypi"
pypi = "awesomeversion"
